### ISSUE TITLE
Не завершается заказ после обновления с 2.1.4 до 2.2.0

### ISSUE THREAD

**Issue by lavkalavkalavka** [yoomoney/cms-opencart15#54]
В консоли браузера:
jquery-1.7.1.min.js:4 POST https://site.ru/admin/index.php?route=sale/order/history&token=1111111111111111111111111111111111111&order_id=11111 500
send @ jquery-1.7.1.min.js:4
ajax @ jquery-1.7.1.min.js:4
(anonymous) @ index.php?route=sale/order/info&token=1111111111111111111111111111111111111&order_id=11111:863
dispatch @ jquery-1.7.1.min.js:3
i @ jquery-1.7.1.min.js:3

В логе сервера:
[Mon Nov 15 15:11:44.739859 2021] [:error] [pid 23619] [client 11.11.11.11:11111] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to YooKassa\\Model\\ReceiptItem::setPrice() must implement interface YooKassa\\Model\\AmountInterface, array given, called in /www/catalog/model/payment/yoomoney/vendor/yoomoney/yookassa-sdk-php/lib/Common/AbstractObject.php on line 109 and defined in /www/catalog/model/payment/yoomoney/vendor/yoomoney/yookassa-sdk-php/lib/Model/ReceiptItem.php:225\nStack trace:\n#0 /www/catalog/model/payment/yoomoney/vendor/yoomoney/yookassa-sdk-php/lib/Common/AbstractObject.php(109): YooKassa\\Model\\ReceiptItem->setPrice(Array)\n#1 /www/catalog/model/payment/yoomoney/vendor/yoomoney/yookassa-sdk-php/lib/Common/AbstractObject.php(185): YooKassa\\Common\\AbstractObject->offsetSet('price', Array)\n#2 /www/catalog/model/payment/yoomoney/vendor/yoomoney/yookassa-sdk-php/lib/Model/ReceiptItem.php(645): YooKassa\\Commo in /www/catalog/model/payment/yoomoney/vendor/yoomoney/yookassa-sdk-php/lib/Model/ReceiptItem.php on line 225, referer: https://site.ru/admin/index.php?route=sale/order/info&token=1111111111111111111111111118&order_id=11111

**Comment by lavkalavkalavka** [comment]
Меняю в админке в истории заказа статус с доставляющегося на завершённый, загорается сообщение "Пожалуйста, подождите", и далее возникает указанная ситуация. Статус заказа при этом не меняется, остаётся доставляющийся.
Видимо, проблема на моменте отправки второго чека.

**Comment by ostulov** [comment]
Добрый день!

Благодарю за обращение, подготовим исправление.
До этого момента Вы можете временно перейти обратно на версию модуля 2.1.4

**Comment by lavkalavkalavka** [comment]
Скажите, пожалуйста, исправлено?

**Comment by ostulov** [comment]
Да, последнее обновление SDK в версии 2.2.2 решает эту ошибку.
